# Generated by Django 5.0.1 on 2024-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('colors', models.CharField(max_length=1000)),
                ('image', models.ImageField(upload_to='product_images/')),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=255)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
