# Generated by Django 5.0.1 on 2024-06-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.CharField(max_length=225, primary_key=True, serialize=False)),
                ('width', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('url', models.CharField(default='', max_length=2000)),
                ('filename', models.CharField(default='', max_length=225)),
                ('size', models.IntegerField(default=0)),
                ('type', models.CharField(default='', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='MyProduct',
            fields=[
                ('id', models.CharField(max_length=1224, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=1224)),
                ('company', models.CharField(default='', max_length=1124)),
                ('price', models.IntegerField(default=0)),
                ('color', models.JSONField(default=dict)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=225)),
                ('featured', models.BooleanField(default=False)),
                ('stock', models.IntegerField(default=0)),
                ('reviews', models.IntegerField(default=0)),
                ('stars', models.FloatField(default=0)),
                ('images', models.ManyToManyField(to='api.images')),
            ],
        ),
    ]
